### ISSUE TITLE
Cannot read properties of undefined (reading 'concat') when include 

### ISSUE THREAD

**Issue by chowks** [mthenw/serverless-go-plugin#50]
Encounter error below when I am trying to include a binary into a function. Or did i miss out something

Error:
```
✖ Stack mhub-post-sales-api-stage failed to deploy (125s)
Environment: linux, node 18.16.0, framework 3.38.0 (local), plugin 7.2.0, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read properties of undefined (reading 'concat')
    at Plugin.compile (/home/ksks1205/projects/mhub-post-sales-api/node_modules/serverless-go-plugin/index.js:155:53)
    at async /home/ksks1205/projects/mhub-post-sales-api/node_modules/serverless-go-plugin/index.js:85:9
    at async /home/ksks1205/projects/mhub-post-sales-api/node_modules/p-map/index.js:57:15
```

serverless.yml:
```
go:
    supportedRuntimes: ["provided.al2023"]
    buildProvidedRuntimeAsBootstrap: true
    cmd: GOARCH=arm64 GOOS=linux go build -tags lambda.norpc -ldflags="-s -w"
```
```
functions:
  my-function:
    handler: ./newhandlers/my_function
     package:
       include:
         - scripts/wkhtmltopdf
```
